config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :users, only: [:index, :show, :edit, :update]
  resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post, optional: true
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  validates :image, :genre_id, :title, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @rank = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
    @posts = Post.all.order(created_at: :desc)
    @post = @posts[0]
    @genre = @post.genre_id
    redirect_to post_path(@genre)
  end

  def show
    @posts = Post.where(genre_id: params[:id])
    @like = Like.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params) if post.user_id == current_user.id
    redirect_to user_path(current_user.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to user_path(current_user.id)
  end

  private
  def post_params
    params.require(:post).permit(:genre_id, :title, :image, :text).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @name = current_user.name
    @posts = current_user.posts
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end



  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_notifications.html.haml
.header
  = link_to root_path do
    .header__left
      Scenery-photo -景色棚-
  .header__right
    .header__right__name
      - if user_signed_in?
        = current_user.name
      - else
        未ログイン
    .header__right__btn
      - if user_signed_in?
        = link_to edit_user_path(current_user) do
          .header__right__btn__color
            user edit
    .header__right__mybtn
      - if user_signed_in?
        = link_to user_path(current_user.id) do
          .header__right__mybtn__color
            my page

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Scenery-post
    -# = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    -# = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %link{:href => "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css", :rel => "stylesheet", :type => "text/css"}/
    %script{:src => "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js", :type => "text/javascript"}

  %body
    = render 'layouts/notifications'
    = yield

app/views/posts/edit.html.haml
.main
  .form
    = form_for (@post) do |f|
      .form__title
        投稿を編集しよう！
      .form__name
        1.写真のジャンル…
      .form__btn
        = f.radio_button :genre_id,1, class: :form__btn__genre
        自然風景
        = f.radio_button :genre_id,2, class: :form__btn__genre
        都市風景
        = f.radio_button :genre_id,3, class: :form__btn__genre
        イベント風景
      .form__input
        .form__input__name
          2.タイトルを決めましょう
        = f.text_field :title, class: :form__input__title, placeholder: 'type a title'
        .form__input__name
          3.あなたの Best shot
        = f.file_field :image, class: :form__input__image
        .form__input__name
          4.写真の思入れを書きましょう
        = f.text_area :text, class: :form__input__text, placeholder: 'type a memory'
        = f.submit '更新する', class: :form__input__submit

app/views/posts/index.html.haml
.wrapper 
  -# = video_tag("/assets/videos/Pexels Videos 1409899.mp4", autoplay: true, loop: true, muted: true, style: "width:100%;")
  .main-content
    .main-content__title
      あなたの最高の一枚を…
    .main-content__text
      Scenery-photo  -景色棚-  は、景色限定で写真を投稿・閲覧できるサービスです
    .main-content__btn
      = link_to new_post_path do
        .main-content__btn__path
          投稿ページへ
.card-section
  .card-section-title
    見たい景色のジャンルの文字を選択！
  .card-list
    = link_to post_path(1) do
      .card-list__item1
        .card-list__item1__title
          自然部門
    = link_to post_path(2) do
      .card-list__item2
        .card-list__item2__title
          都市部門
    = link_to post_path(3) do
      .card-list__item3
        .card-list__item3__title
          イベント部門
.card-section
  .card-section-title
    全景色人気ランキングTOP3！
  .ranks
    - @rank.each do |post|
      .ranks__rank
        .ranks__rank__title
          タイトル：
          = post.title
        .ranks__rank__name
          投稿者：
          = post.user.name
        .ranks__rank__like
          = icon('far', 'thumbs-up')
          = post.likes.count
        .ranks__rank__image
          = image_tag post.image
        

.footer
  .footer__message
    Meeting new photos is waiting…

app/views/posts/new.html.haml
.main
  .form
    = form_for (@post) do |f|
      .form__title
        こちらのフォームで投稿してみよう！
      .form__name
        1.写真のジャンル…
      .form__btn
        = f.radio_button :genre_id,1, class: :form__btn__genre
        自然風景
        = f.radio_button :genre_id,2, class: :form__btn__genre
        都市風景
        = f.radio_button :genre_id,3, class: :form__btn__genre
        イベント風景
      .form__input
        .form__input__name
          2.タイトルを決めましょう
        = f.text_field :title, class: :form__input__title, placeholder: 'type a title'
        .form__input__name
          3.あなたの Best shot
        = f.file_field :image, class: :form__input__image
        .form__input__name
          4.写真の思入れを書きましょう
        = f.text_area :text, class: :form__input__text, placeholder: 'type a memory'
        = f.submit '投稿する', class: :form__input__submit

app/views/posts/show.html.haml
.contents
  - @posts.each do |post|
    .content
      .content__title
        タイトル：
        = post.title
      .content__name
        投稿者：
        = post.user.name
      .content__image
        = image_tag post.image
      .content__text
        写真のストーリー：
        = post.text
      .content__like
        .content__like__count
          -if current_user.already_liked?(post)
            = icon('far', 'thumbs-down')
            = button_to '取り消す', post_like_path(post), method: :delete
          - else
            = icon('far', 'thumbs-up')
            = button_to 'いいね', post_likes_path(post)
          = post.likes.count
        .content__like__users
          - post.liked_users.each do |user|
            ・
            = user.name

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/index.html.haml
.user-main
  .persons
    ユーザー一覧
    - @users.each do |user|
      .person
      = user.id
      = user.name
      = user.email
  .person_likes
    -# いいねした投稿
    -# - @user.liked_posts.each do |post| 
    -#   = post.user.name
    -#   = post.title 
.link
  = link_to root_path do
    トップページへ戻る
      

app/views/users/show.html.haml
.contents
  - @posts.each do |post|
    .content
      .content__title
        タイトル：
        = post.title
      .content__image
        = image_tag post.image
      .content__text
        写真のストーリー：
        = post.text
      .content__operation
        .content__operation__edit
          - if user_signed_in? && current_user.id == post.user_id
            = link_to edit_post_path(post) do
              edit
        .content__operation__destroy
          - if user_signed_in? && current_user.id == post.user_id
            = link_to post_path(post), method: :delete, data: {confirm: "削除してもよろしいですか？"} do
              delete
      .content__like
        .content__like__count
          -if current_user.already_liked?(post)
            = icon('far', 'thumbs-down')
            = button_to '取り消す', post_like_path(post), method: :delete
          - else
            = icon('far', 'thumbs-up')
            = button_to 'いいね', post_likes_path(post)
          = post.likes.count
        .content__like__users
          - post.liked_users.each do |user|
            = user.name